/* @flow */
export const INIT_AUTH: string = 'INIT_AUTH'

export const SIGNIN_SUCCESS: string = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL: string = 'SIGNIN_FAIL'

export const SIGNOUT_SUCCESS: string = 'SIGNOUT_SUCCESS'

export const CREATE_PROJECT_SUCCESS: string = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_ERROR: string = 'CREATE_PROJECT_ERROR'
export const REMOVE_PROJECT_SUCCESS: string = 'REMOVE_PROJECT_SUCCESS'
export const REMOVE_PROJECT_ERROR: string = 'REMOVE_PROJECT_ERROR'
export const UPDATE_PROJECT_SUCCESS: string = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_ERROR: string = 'UPDATE_PROJECT_ERROR'
export const LOAD_PROJECT_SUCCESS: string = 'LOAD_PROJECT_SUCCESS'
export const LOAD_PROJECT_ERROR: string = 'LOAD_PROJECT_ERROR'
export const LOAD_PROJECTS_SUCCESS: string = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_ERROR: string = 'LOAD_PROJECTS_ERROR'
